apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-trader.fullname" . }}
  labels:
    {{- include "ai-trader.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ai-trader.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ai-trader.selectorLabels" . | nindent 8 }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "ai-trader.serviceAccountName" . }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: SLACK_WEBHOOK_URL
              value: {{ .Values.alerting.slackWebhookUrl | quote }}
            - name: PAGERDUTY_ROUTING_KEY
              value: {{ .Values.alerting.pagerdutyRoutingKey | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /_readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health/deep
              port: http
            failureThreshold: 10
            periodSeconds: 6
