{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-trader.serviceAccountName" . }}
  labels:
    {{- include "ai-trader.labels" . | nindent 4 }}
{{- end }}
